config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'events#index'
  resources :users, only: %i[new create show]
  resources :events do
    member do
      get "invite"
    end
  end
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations, source: :attendee
  belongs_to :creator, class_name: 'User'

  validates :name, :description, :location, :date, presence: true

  scope :past, -> { where(['date < ?', Date.today]) }
  scope :upcoming, -> { where(['date > ?', Date.today]) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id, class_name: 'Event'
  has_many :invitations, foreign_key: :attendee
  has_many :attended_events, through: :invitations

  validates :name, presence: true
  validates_uniqueness_of :name

  scope :past, -> { where(['date < ?', Date.today]) }
  scope :upcoming, -> { where(['date > ?', Date.today]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    redirect_to root_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user, except: [:index]

  def index
    @past = Event.past
    @upcoming = Event.upcoming
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to events_path
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @users = User.where.not(name: @event.creator.name)
  end

  def invite
    @event = Event.find(params[:id])
    @event.attendees << User.where.not(name: @event.creator.name)
    redirect_to current_user
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(name: params[:session][:user])
    @user ||= User.find(params[:session][:user].to_i)

    if @user
      session[:user_id] = @user.id
      session[:username] = @user.name
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    redirect_to user_path(current_user) if logged_in?
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      session[:username] = @user.name
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.attended_events.upcoming
    @prev_events = @user.attended_events.past
  end

  def destroy
    session[:user_id] = nil
    session[:username] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_sign_in_out
    out = ''
    if logged_in?
      out << link_to(current_user.name, user_path(session[:user_id]))
      out << '</br>'
      out << link_to('Sign out', logout_path, method: :delete)
    else
      out << link_to('login', sign_in_path)
      out << '</br>'
      out << link_to('Sign up', new_user_path)
    end

    out.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def created_events(user, name, events, title)
    render partial: name, locals: { obj: events, title: title } if user.events.size.positive?
  end

  def attended_events(user, name, events, title)
    return unless user.attended_events.size.positive?

    render partial: name, locals: { obj: events, title: title } if events.size.positive?
  end
end

app/views/events/index.html.erb
<h4>Events</h4>
<h4>Past Event</h4>
<% @past.each do |event| %>
	<h5><%= link_to event.name, event_path(event) %></h5>
    <p><%= event.description %></p>
    <p><strong>Location: </strong><small><%= event.location %></small></p>
    <p><strong>Date: </strong>
    <small>
        <strong><%= event.date.to_s.split(' ').first %> </strong>
        <em><%= event.date.to_s.split(' ')[1] %></em>
    </small>
    </p>
<% end %>
<br>
<h4>Upcoming Event</h4>
<% @upcoming.each do |event| %>
	<h5><%= link_to event.name, event_path(event) %></h5>
    <p><%= event.description %></p>
    <p><strong>Location: </strong><small><%= event.location %></small></p>
    <p><strong>Date: </strong>
    <small>
        <strong><%= event.date.to_s.split(' ').first %> </strong>
        <em><%= event.date.to_s.split(' ')[1] %></em>
    </small>
    </p>
<% end %>

app/views/events/new.html.erb
<h1>Add Event</h1>
<%= form_for(@event) do |f| %>
	<div>
	    <%= f.text_field :name, autofocus: true, placeholder: "Event Title" %>
	</div>
	<div>
	    <%= f.text_area :description, placeholder: "Event Description" %>
	</div>
	<div>
	    <%= f.text_field :location, placeholder: "Event Location" %>
	</div>
	  <div>
	    <%= f.datetime_select :date, :ampm => true, :minute_step => 15 %>
	</div>
	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/events/show.html.erb
<h5><%= @event.name %><br><small>Owner: <%= @event.creator.name  %> </small></h5>
<p><%= @event.description %></p>
<p><strong>Location: </strong><small><%= @event.location %></small></p>
<p><strong>Date: </strong>
<small>
    <strong><%= @event.date.to_s.split(' ').first %> </strong>
    <em><%= @event.date.to_s.split(' ')[1] %></em>
</small>
</p>

<br>
<h5>List of Attendees</h5>
<% @event.attendees.each do |attendee|%>
    <p><strong><%= attendee.name %></strong></p>
<% end %>
<br>
<h5 class="card-title border-bottom pb-2">Invite Friends</h5>
<% @users.each do |user| %>
    <p><%= user.name %> &mdash; <%= link_to 'Invite', invite_event_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <ul>
      <li>
       <%= link_to 'All Events', events_path %>
      </li>
      <li>
        <%= link_to 'Create Event', new_event_path %>        
      </li>
    </ul>
    <br>
    <%= show_sign_in_out %>
    <%= yield %>
  </body>
</html>

app/views/users/_events.erb
<h4><%= title %></h4>
<% obj.each do |event| %>
	<h5><%= link_to event.name, event_path(event) %></h5>
    <p><%= event.description %></p>
    <p><strong>Location: </strong><small><%= event.location %></small></p>
    <p><strong>Date: </strong>
    <small>
        <strong><%= event.date.to_s.split(' ').first %> </strong>
        <em><%= event.date.to_s.split(' ')[1] %></em>
    </small>
    </p>
<% end %>

app/views/users/new.html.erb
<h1>Create Account</h1>
<%= form_for(@user) do |f| %>
	<div>
    	<%= f.text_field :name, autofocus: true, placeholder: "Enter a username" %>
	</div>
	<div>
  		<%= f.submit %>
	</div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %> show page</h1>
<%= created_events(@user, 'users/events', @user.events, 'List of created events')  %>
<%= attended_events(@user, 'users/events', @upcoming_events,'List of upcoming events')  %>
<%= attended_events(@user, 'users/events', @prev_events,'List of Previously attended events')  %>